# Generated by Django 5.2.8 on 2025-11-14 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_member_direcction_member_email_member_identification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='direcction',
        ),
        migrations.RemoveField(
            model_name='member',
            name='email',
        ),
        migrations.RemoveField(
            model_name='member',
            name='identification',
        ),
    ]
