# Generated by Django 5.2.8 on 2025-11-14 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_remove_member_direcction_remove_member_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='direcction',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='email',
            field=models.EmailField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='identification',
            field=models.IntegerField(null=True),
        ),
    ]
